metadata.format.version = "1.1"

[versions]
minestom-ce = "438338381e"
minestom = "954e8b3915"
blossom = "1.3.0"
shadowJar = "7.0.0"
tinylog = "2.5.0"
jline = "3.21.0"

[libraries]
minestomce = { group = "dev.hollowcube", name = "minestom-ce", version.ref = "minestom-ce" }
minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }
tinylog-api = { group = "org.tinylog", name = "tinylog-api", version.ref = "tinylog" }
tinylog-impl = { group = "org.tinylog", name = "tinylog-impl", version.ref = "tinylog" }
tinylog-slf4j = { group = "org.tinylog", name = "slf4j-tinylog", version.ref = "tinylog" }
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jline-jansi = { group = "org.jline", name = "jline-terminal-jansi", version.ref = "jline" }

[bundles]
logging = ["tinylog-api", "tinylog-impl", "tinylog-slf4j"]
terminal = ["jline", "jline-jansi"]

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }